# 同一手牌のまま、見える危険度だけを一方向へ強める例
KEEP_ONLY
SCENE "宣言牌危険度・弱"
LOCK SELF HAND ALL
SET KAMI RIVER 2 7m
END
SCENE "宣言牌危険度・中"
LOCK SELF HAND ALL
SET KAMI RIVER 2 8m
END
SCENE "宣言牌危険度・強"
LOCK SELF HAND ALL
REACH KAMI ON BEFORE SELF RIVER 10
SET KAMI RIVER 2 9m
END
